--- 
title: "Project One"
subtitle: Group Two
author:
- Vinicio Haro
- Sang Yoon (Andy) Hwang
- Julian McEachern
- Jeremy O'Brien
- Bethany Poulin
date: "22 October 2019"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
output: bookdown::pdf_book
subparagraph: true
classoption: openany
---

# Overview {-#overview}

Project 1 Overview. Explanation of process, etc. 

## Dependencies {-#dependencies}

The following R libraries were used to complete Project 1. 

```{r getting-started, echo=T, eval=F}

# Processing

library(readxl)
library(tidyverse)
library(zoo)
library(janitor)

## Insert Additional Packages Here

# Graphing
library(ggplot2)
library(grid)
library(gridExtra)

## Insert Additional Packages Here

# Timeseries 
library(zoo)

## Insert Additional Packages Here

# Math
library(forecast)
library(urca)

## Insert Additional Packages Here

# Formatting
require(knitr)
require(kableExtra)
require(default)
```

## Data Aquisition {-#aquisition}

Data was stored within our group repository and imported below using the `readxl` package. 

```{r, eval=F}
atm_data <- read_excel("data/ATM624Data.xlsx") 
power_data <- read_excel("data/ResidentialCustomerForecastLoad-624.xlsx") 
pipe1_data <- read_excel("data/Waterflow_Pipe1.xlsx")
pipe2_data <- read_excel("data/Waterflow_Pipe2.xlsx")
```


```{r include=FALSE}

### ONCE COMPLETE WE CAN INSERT ALL PACKAGES HERE FOR AUTO-BIB CREATION

# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
